from dataclasses import dataclass, field

# ---------------------------------------------------------------------------
# Streaming Events — the only event system in use.
# Chunk-based events have been removed in Phase 4C.
# See legacy/chunk_pipeline/ for historical reference.
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class StreamingSessionStartedEvent:
    session_id: str
    event_seq: int
    wall_timestamp: float
    session_time_ms: float
    metadata: dict = field(default_factory=dict)

@dataclass(frozen=True)
class StreamingAudioFrameReceivedEvent:
    session_id: str
    event_seq: int
    wall_timestamp: float
    session_time_ms: float
    sequence_number: int
    is_speech: bool
    frame_delay_ms: float

@dataclass(frozen=True)
class StreamingSpeechStartedEvent:
    session_id: str
    event_seq: int
    wall_timestamp: float
    session_time_ms: float
    correlation_id: str

@dataclass(frozen=True)
class StreamingSpeechEndedEvent:
    session_id: str
    event_seq: int
    wall_timestamp: float
    session_time_ms: float
    correlation_id: str

@dataclass(frozen=True)
class StreamingPartialTranslationEvent:
    session_id: str
    event_seq: int
    wall_timestamp: float
    session_time_ms: float
    text_delta: str
    cumulative_text: str
    correlation_id: str
    participant_identity: str = ""

@dataclass(frozen=True)
class StreamingTranslationCompletedEvent:
    session_id: str
    event_seq: int
    wall_timestamp: float
    session_time_ms: float
    full_text: str
    correlation_id: str
    metrics: dict = field(default_factory=dict)
    participant_identity: str = ""

@dataclass(frozen=True)
class StreamingSessionClosedEvent:
    session_id: str
    event_seq: int
    wall_timestamp: float
    session_time_ms: float
    metrics: dict = field(default_factory=dict)

@dataclass(frozen=True)
class StreamingBackpressureEvent:
    session_id: str
    event_seq: int
    wall_timestamp: float
    session_time_ms: float
    queue_depth: int
    policy: str

@dataclass(frozen=True)
class StreamingStateChangedEvent:
    session_id: str
    event_seq: int
    wall_timestamp: float
    session_time_ms: float
    old_state: str
    new_state: str

@dataclass(frozen=True)
class StreamingRuntimeErrorEvent:
    session_id: str
    event_seq: int
    wall_timestamp: float
    session_time_ms: float
    error_message: str
    correlation_id: str = ""

@dataclass(frozen=True)
class StreamingTranslationAudioEvent:
    """
    Carries raw translated audio bytes generated by the model in real-time.
    Distinct from StreamingAudioFrameReceivedEvent (which is a diagnostic/telemetry
    event for input mic frames). Reusing input telemetry events is not feasible
    as they do not contain raw binary payload fields.
    """
    session_id: str
    event_seq: int
    wall_timestamp: float
    session_time_ms: float
    audio_data: bytes
    mime_type: str
    correlation_id: str = ""
    participant_identity: str = ""

