from enum import Enum

class PipelineEvent(str, Enum):
    SESSION_STARTED = "SESSION_STARTED"
    SESSION_ENDED = "SESSION_ENDED"
    MIC_FRAME_RECEIVED = "MIC_FRAME_RECEIVED"
    VAD_DECISION = "VAD_DECISION"
    AUDIO_SENT_TO_GEMINI = "AUDIO_SENT_TO_GEMINI"
    GEMINI_WS_FRAME_RECEIVED = "GEMINI_WS_FRAME_RECEIVED"
    TRANSLATED_TEXT_RECEIVED = "TRANSLATED_TEXT_RECEIVED"
    TRANSLATED_AUDIO_RECEIVED = "TRANSLATED_AUDIO_RECEIVED"
    TEXT_PUBLISHED = "TEXT_PUBLISHED"
    AUDIO_PUBLISHED = "AUDIO_PUBLISHED"
    PIPELINE_ERROR = "PIPELINE_ERROR"
